repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [
            "--max-line-length=100",
            "--ignore=D100,D101,D103,D107,D200,D400,E501,F401,F841,E722,F541,E402,W503",
            "--exclude=venv*,build,dist,.*"
        ]

-   repo: local
    hooks:
    -   id: conventional-commit-check
        name: 检查约定式提交格式
        description: 确保提交消息符合约定式提交规范
        entry: tools/commit-msg
        language: script
        stages: [commit-msg] 