name: Setup Git Hooks

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/pre-commit'
      - 'tools/commit-msg'
      - '.pre-commit-config.yaml'
      - '.github/workflows/setup-hooks.yml'

jobs:
  setup-hooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Make hook scripts executable
      run: |
        chmod +x tools/pre-commit
        chmod +x tools/commit-msg
        chmod +x tools/generate_changelog.py
        chmod +x tools/version-bump
    
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit --version
    
    - name: Document pre-commit setup
      run: |
        if [ ! -f CONTRIBUTING.md ]; then
          echo "# 贡献指南" > CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo "感谢您对计划管理工具的贡献兴趣！" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
        fi
        
        # 检查是否已有pre-commit部分
        if ! grep -q "## 代码质量检查" CONTRIBUTING.md; then
          echo "## 代码质量检查" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo "本项目使用 pre-commit 进行代码质量检查。请按照以下步骤设置：" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo '```bash' >> CONTRIBUTING.md
          echo "# 安装pre-commit" >> CONTRIBUTING.md
          echo "pip install pre-commit" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo "# 安装git hooks" >> CONTRIBUTING.md
          echo "pre-commit install" >> CONTRIBUTING.md
          echo "pre-commit install --hook-type commit-msg" >> CONTRIBUTING.md
          echo '```' >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo "pre-commit将在每次提交前自动运行以下检查：" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
          echo "- black：代码格式化" >> CONTRIBUTING.md
          echo "- flake8：代码风格检查" >> CONTRIBUTING.md
          echo "- mypy：类型检查" >> CONTRIBUTING.md
          echo "- 约定式提交格式验证" >> CONTRIBUTING.md
          echo "" >> CONTRIBUTING.md
        fi
    
    - name: Commit changes if CONTRIBUTING.md was modified
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CONTRIBUTING.md
        
        # 只有当CONTRIBUTING.md有变化时才提交
        if git diff --staged --quiet; then
          echo "无需提交，CONTRIBUTING.md 未修改"
        else
          git commit -m "docs: 更新贡献指南，添加pre-commit设置说明"
          git push
        fi 